# This is a basic workflow to help you get started with Actions

name: Github actions robot framework integration jira

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ staging ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        run:  
              sudo mkdir ${{ github.workspace }}/reports
              sudo chmod -R 777 ${{ github.workspace }}/reports
      - name: Robot Framework
        uses: joonvena/robotframework-docker-action@v0.1
        env:
          BROWSER: chrome
          ROBOT_TESTS_DIR: ${{ github.workspace }}/robot_tests
          ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
