# This is a basic workflow to help you get started with Actions

name: Github actions robot framework integration jira

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [staging]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Dump GitHub context
       env:
          GITHUB_CONTEXT: ${{ tojson(github) }}
          ENVIRONMENT: ${{ github.event.push.ref }}
       run: |
            echo ${{ github.event.commits[0].url }}
#echo "$GITHUB_CONTEXT"