# This is a basic workflow to help you get started with Actions

name: Github actions robot framework integration jira

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Extracts Parameters Jira
       run: |
            echo ${{ github.workspace }}
            COMMIT=${{ github.event.repository.commits_url }}
            SHA="/${{ github.sha }}"
            COMMIT_URL=$(echo "${COMMIT/{\/sha\}/$SHA}")
            curl -s $COMMIT_URL  | jq . > COMMIT_CONTEXT.json
            echo "::set-env name=MESSAGE::$(jq .commit.message COMMIT_CONTEXT.json)"
            echo "::set-env name=FILE::$(jq .files[0].filename COMMIT_CONTEXT.json)"
            echo "::set-env name=FILE_NAME::$(basename $FILE)"
     - name: Execute Test
       run: |
            echo $FILE_NAME