on:
  push:
    #Change staging
    branches: [staging]

name: Test Transition Issue

jobs:
  test-transition-issue:
    runs-on: ubuntu-latest
    name: Transition Issue
    steps:
      - uses: actions/checkout@v2
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      - run: |
          curl -u ${{ secrets.JIRA_USER_EMAIL }}:${{ secrets.JIRA_API_TOKEN }} ${{ secrets.JIRA_BASE_URL }}/rest/api/2/issue/PAT-1 | jq . > Context_Jira.json
          echo Environment: $(jq .fields.customfield_10032.value Context_Jira.json)
          echo Test Type: $(jq .fields.customfield_10033.value Context_Jira.json)
          echo Customer Group: $(jq .fields.customfield_10035.value Context_Jira.json)
          echo Customer: $(jq .fields.customfield_10035.value Context_Jira.json)
          echo Customer: $(jq .fields.customfield_10035.child.value Context_Jira.json)

#          cat ${{ github.workspace }}/js/a.txt ${{ github.workspace }}/js/b.txt > c.txt
#          cat c.txt
#          cd js
#          cat b.txt

#        uses: atlassian/gajira-login@master
#        env:
#          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
#          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
#          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
#
#      - name: Transition issue
#        uses: atlassian/gajira-transition@master
#        with:
#          issue: 'AIJX-6'
#          transition: "Listo"
#      - name: Comment on issue
#        uses: atlassian/gajira-comment@master
#        with:
#          issue: 'AIJX-6'
#          comment: "Test Executed Successfully, Report: \n https://lf-automated-tests-framework.s3.amazonaws.com/cameo/cameo.html"
